---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# .. Copyright (C) 2022 VEXXHOST, Inc.
# .. SPDX-License-Identifier: Apache-2.0

# Default variables
# =================

# .. contents:: Sections
#    :local:


# .. envvar:: sysctls [[[
#
# List of ``sysctl`` parameters to set
sysctls:
  - name: net.ipv4.tcp_timestamps
    value: 0
  - name: net.ipv4.tcp_sack
    value: 1
  - name: net.core.netdev_budget
    value: 1000
  - name: net.core.netdev_max_backlog
    value: 250000
  - name: net.core.rmem_max
    value: 4194304
  - name: net.core.wmem_max
    value: 4194304
  - name: net.core.rmem_default
    value: 4194304
  - name: net.core.wmem_default
    value: 4194304
  - name: net.core.optmem_max
    value: 4194304
  - name: net.ipv4.tcp_rmem
    value: 4096 87380 4194304
  - name: net.ipv4.tcp_wmem
    value: 4096 65536 4194304
  - name: net.ipv4.tcp_low_latency
    value: 1
  - name: net.ipv4.tcp_adv_win_scale
    value: 1
  - name: net.ipv4.neigh.default.gc_thresh1
    value: 128
  - name: net.ipv4.neigh.default.gc_thresh2
    value: 28872
  - name: net.ipv4.neigh.default.gc_thresh3
    value: 32768
  - name: net.ipv6.neigh.default.gc_thresh1
    value: 128
  - name: net.ipv6.neigh.default.gc_thresh2
    value: 28872
  - name: net.ipv6.neigh.default.gc_thresh3
    value: 32768
                                                                   # ]]]
