apiVersion: v1
appVersion: v1.0.0
description: OpenStack-Helm Glance
home: https://docs.openstack.org/glance/latest/
icon: https://www.openstack.org/themes/openstack/images/project-mascots/Glance/OpenStack_Project_Glance_vertical.png
maintainers:
- name: OpenStack-Helm Authors
name: glance
sources:
- https://opendev.org/openstack/glance
- https://opendev.org/openstack/openstack-helm
version: 0.4.20
