---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# .. Copyright (C) 2022 VEXXHOST, Inc.
# .. SPDX-License-Identifier: Apache-2.0

# Default variables
# =================

# .. contents:: Sections
#    :local:


# .. envvar:: openstack_helm_magnum_image_repository [[[
#
# Image repository location to be prefixed for all images
openstack_helm_magnum_image_repository: "{{ atmosphere_image_repository | default('quay.io/vexxhost') }}"

                                                                   # ]]]
# .. envvar:: openstack_helm_magnum_image_tag [[[
#
# Image tag for container
openstack_helm_magnum_image_tag: "{{ atmosphere_openstack_release | default('wallaby') }}"

                                                                   # ]]]
# .. envvar:: openstack_helm_magnum_heat_image_tag [[[
#
# Image tag for Heat to be used for jobs running via Helm hooks
openstack_helm_magnum_heat_image_tag: "{{ atmosphere_openstack_release | default('wallaby') }}"

                                                                   # ]]]
# .. envvar:: openstack_helm_magnum_values [[[
#
# Overrides for Helm chart values
openstack_helm_magnum_values: {}

                                                                   # ]]]
# .. envvar:: openstack_helm_magnum_images [[[
#
# List of images for magnum clusters
openstack_helm_magnum_images:
  - name: ubuntu-2004-v1.23.13
    source_url:  https://object-storage.public.mtl1.vexxhost.net/swift/v1/a91f106f55e64246babde7402c21b87a/magnum-capi/
    image_file: ubuntu-2004-v1.23.13.qcow2
    disk_format: qcow2
    container_format: bare
  - name: ubuntu-2004-v1.24.7
    source_url:  https://object-storage.public.mtl1.vexxhost.net/swift/v1/a91f106f55e64246babde7402c21b87a/magnum-capi/
    image_file: ubuntu-2004-v1.24.7.qcow2
    disk_format: qcow2
    container_format: bare
  - name: ubuntu-2004-v1.25.3
    source_url:  https://object-storage.public.mtl1.vexxhost.net/swift/v1/a91f106f55e64246babde7402c21b87a/magnum-capi/
    image_file: ubuntu-2004-v1.25.3.qcow2
    disk_format: qcow2
    container_format: bare

                                                                   # ]]]
