# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

vault_secret_kubeconfig: "{{ kubeconfig_path | default('/etc/kubernetes/admin.conf') }}"
vault_secrets_bootstrap_group: controllers

# vault_secrets:
#   - path: molecule
#     data:
#       foo: bar
#       simple: secret
#       record: asdcascascascsaAAAA
#       new_key: new_value
#       temp_token:
#       temp_token2:
#       temp_token3:
#         constraints:
#           - length=32
#   - path: application/config
#     data:
#       database_url: postgres://localhost:5432/mydb_updated
#       api_key: secret123
#       debug_mode: "false"
#       session_secret:
#         constraints:
#           - lower=false
#           - length=15
#       jwt_secret:
#         constraints:
#           - special=true
#           - length=48
#   - path: test/new-path
#     data:
#       test_key1:
#       test_key2:
#   - path: test/empty-values
#     data:
#       username: ""
#       password:
#       api_key: test
#       token:
#       test:
#         constraints:
#           - special=true
#           - length=40
#   - path: infrastructure/percona-xtradb
#     data:
#       clustercheck:
#       monitor:
#       operator:
#       proxyadmin:
#       replication:
#       root:
#       xtrabackup:
