# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

transceiver_exporter_helm_release_name: transceiver-exporter
transceiver_exporter_helm_chart_path: "../../charts/transceiver-exporter/"
transceiver_exporter_helm_chart_ref: /usr/local/src/transceiver-exporter

transceiver_exporter_helm_release_namespace: monitoring
transceiver_exporter_helm_kubeconfig: "{{ kubeconfig_path | default('/etc/kubernetes/admin.conf') }}"
transceiver_exporter_helm_values: {}
