# Copyright (c) 2022 VEXXHOST, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

_openstack_helm_endpoints_ignore:
  - ceph_object_store
  - cloudwatch
  - cluster_domain_suffix
  - compute_spice_proxy
  - fluentd
  - ingress
  - kube_dns
  - ldap
  - libvirt_exporter
  - local_image_registry
  - monitoring
  - object_store
  - oci_image_registry
  - prometheus_rabbitmq_exporter

_openstack_helm_endpoints_oslo_db:
  oslo_db:
    hosts:
      default: percona-xtradb-haproxy

_openstack_helm_endpoints_oslo_messaging:
  oslo_messaging:
    statefulset: null
    hosts:
      default: "rabbitmq-{{ openstack_helm_endpoints_chart }}"

_openstack_helm_endpoints_oslo_cache:
  oslo_cache:
    auth:
      memcache_secret_key: "{{ openstack_helm_endpoints_memcached_secret_key }}"

_openstack_helm_endpoints_identity:
  identity:
    auth:
      admin:
        region_name: "{{ openstack_helm_endpoints_keystone_region_name }}"
        username: "admin-{{ openstack_helm_endpoints_keystone_region_name }}"
        password: "{{ openstack_helm_endpoints_keystone_admin_password }}"
    hosts:
      default: keystone-api
    scheme:
      public: https
    host_fqdn_override:
      public:
        host: "{{ openstack_helm_endpoints_keystone_api_host }}"
    port:
      api:
        default: 5000
        public: 443
  oslo_db:
    auth:
      keystone:
        password: "{{ openstack_helm_endpoints_keystone_mariadb_password }}"
  oslo_messaging:
    auth:
      keystone:
        password: "{{ openstack_helm_endpoints_keystone_rabbitmq_password }}"

_openstack_helm_endpoints_image:
  identity:
    auth:
      glance:
        region_name: "{{ openstack_helm_endpoints_glance_region_name }}"
        username: "glance-{{ openstack_helm_endpoints_glance_region_name }}"
        password: "{{ openstack_helm_endpoints_glance_keystone_password }}"
  image:
    scheme:
      public: https
    host_fqdn_override:
      public:
        host: "{{ openstack_helm_endpoints_glance_api_host }}"
    port:
      api:
        public: 443
  oslo_db:
    auth:
      glance:
        password: "{{ openstack_helm_endpoints_glance_mariadb_password }}"
  oslo_messaging:
    auth:
      glance:
        password: "{{ openstack_helm_endpoints_glance_rabbitmq_password }}"

_openstack_helm_endpoints_volumev3:
  identity:
    auth:
      cinder:
        region_name: "{{ openstack_helm_endpoints_cinder_region_name }}"
        username: "cinder-{{ openstack_helm_endpoints_cinder_region_name }}"
        password: "{{ openstack_helm_endpoints_cinder_keystone_password }}"
  volumev3:
    scheme:
      public: https
    host_fqdn_override:
      public:
        host: "{{ openstack_helm_endpoints_cinder_api_host }}"
    port:
      api:
        public: 443
  oslo_db:
    auth:
      cinder:
        password: "{{ openstack_helm_endpoints_cinder_mariadb_password }}"
  oslo_messaging:
    auth:
      cinder:
        password: "{{ openstack_helm_endpoints_cinder_rabbitmq_password }}"

_openstack_helm_endpoints_placement:
  identity:
    auth:
      placement:
        region_name: "{{ openstack_helm_endpoints_placement_region_name }}"
        username: "placement-{{ openstack_helm_endpoints_placement_region_name }}"
        password: "{{ openstack_helm_endpoints_placement_keystone_password }}"
  oslo_db:
    auth:
      placement:
        password: "{{ openstack_helm_endpoints_placement_mariadb_password }}"
  placement:
    scheme:
      public: https
    host_fqdn_override:
      public:
        host: "{{ openstack_helm_endpoints_placement_api_host }}"
    port:
      api:
        public: 443

_openstack_helm_endpoints_key_manager:
  identity:
    auth:
      barbican:
        region_name: "{{ openstack_helm_endpoints_barbican_region_name }}"
        username: "barbican-{{ openstack_helm_endpoints_barbican_region_name }}"
        password: "{{ openstack_helm_endpoints_barbican_keystone_password }}"
  oslo_db:
    auth:
      barbican:
        password: "{{ openstack_helm_endpoints_barbican_mariadb_password }}"
  key_manager:
    scheme:
      public: https
    host_fqdn_override:
      public:
        host: "{{ openstack_helm_endpoints_barbican_api_host }}"
    port:
      api:
        public: 443

_openstack_helm_endpoints_network:
  identity:
    auth:
      neutron:
        region_name: "{{ openstack_helm_endpoints_neutron_region_name }}"
        username: "neutron-{{ openstack_helm_endpoints_neutron_region_name }}"
        password: "{{ openstack_helm_endpoints_neutron_keystone_password }}"
  network:
    scheme:
      public: https
    host_fqdn_override:
      public:
        host: "{{ openstack_helm_endpoints_neutron_api_host }}"
    port:
      api:
        public: 443
  oslo_db:
    auth:
      neutron:
        password: "{{ openstack_helm_endpoints_neutron_mariadb_password }}"
  oslo_messaging:
    auth:
      neutron:
        password: "{{ openstack_helm_endpoints_neutron_rabbitmq_password }}"

_openstack_helm_endpoints_compute:
  identity:
    auth:
      nova:
        region_name: "{{ openstack_helm_endpoints_nova_region_name }}"
        username: "nova-{{ openstack_helm_endpoints_nova_region_name }}"
        password: "{{ openstack_helm_endpoints_nova_keystone_password }}"
  compute:
    scheme:
      public: https
    host_fqdn_override:
      public:
        host: "{{ openstack_helm_endpoints_nova_api_host }}"
    port:
      api:
        public: 443
  oslo_db:
    auth:
      nova:
        password: "{{ openstack_helm_endpoints_nova_mariadb_password }}"
  oslo_messaging:
    auth:
      nova:
        password: "{{ openstack_helm_endpoints_nova_rabbitmq_password }}"

_openstack_helm_endpoints_oslo_db_api:
  oslo_db_api:
    auth:
      nova:
        password: "{{ openstack_helm_endpoints_nova_mariadb_password }}"
    hosts:
      default: percona-xtradb-haproxy

_openstack_helm_endpoints_oslo_db_cell0:
  oslo_db_cell0:
    auth:
      nova:
        password: "{{ openstack_helm_endpoints_nova_mariadb_password }}"
    hosts:
      default: percona-xtradb-haproxy

_openstack_helm_endpoints_compute_metadata:
  compute_metadata:
    secret: "{{ openstack_helm_endpoints_neutron_metadata_secret }}"
    hosts:
      public: nova-metadata
    port:
      metadata:
        public: 8775

_openstack_helm_endpoints_compute_novnc_proxy:
  compute_novnc_proxy:
    scheme:
      public: https
    host_fqdn_override:
      public:
        host: "{{ openstack_helm_endpoints_nova_novnc_host }}"
    port:
      novnc_proxy:
        public: 443

_openstack_helm_endpoints_baremetal:
  identity:
    auth:
      ironic:
        region_name: "{{ openstack_helm_endpoints_ironic_region_name }}"
        username: "ironic-{{ openstack_helm_endpoints_ironic_region_name }}"
        password: "{{ openstack_helm_endpoints_ironic_keystone_password }}"
  baremetal:
    scheme:
      public: https
    host_fqdn_override:
      public:
        host: "{{ openstack_helm_endpoints_ironic_api_host }}"
    port:
      api:
        public: 443
  oslo_db:
    auth:
      ironic:
        password: "{{ openstack_helm_endpoints_ironic_mariadb_password }}"
  oslo_messaging:
    auth:
      ironic:
        password: "{{ openstack_helm_endpoints_ironic_rabbitmq_password }}"

_openstack_helm_endpoints_dns:
  identity:
    auth:
      designate:
        region_name: "{{ openstack_helm_endpoints_designate_region_name }}"
        username: "desigante-{{ openstack_helm_endpoints_designate_region_name }}"
        password: "{{ openstack_helm_endpoints_designate_keystone_password }}"
  dns:
    scheme:
      public: https
    host_fqdn_override:
      public:
        host: "{{ openstack_helm_endpoints_designate_api_host }}"
    port:
      api:
        public: 443
  oslo_db:
    auth:
      designate:
        password: "{{ openstack_helm_endpoints_designate_mariadb_password }}"
  oslo_messaging:
    auth:
      designate:
        password: "{{ openstack_helm_endpoints_designate_rabbitmq_password }}"

_openstack_helm_endpoints_mdns:
  name: minidns
  hosts:
    default: minidns
    public: designate-mdns
  host_fqdn_override:
    default: "{{ openstack_helm_endpoints_designate_api_host }}"
  path:
    default: /
  scheme:
    default: 'tcp'
  port:
    ipc:
      default: 5354

_openstack_helm_endpoints_powerdns:
  auth:
    service:
      token: chiave_segreta
  hosts:
    default: powerdns
  host_fqdn_override:
    default: "{{ openstack_helm_endpoints_designate_api_host }}"
  port:
    powerdns_api:
      default: 8081
    powerdns:
      default: 53

_openstack_helm_endpoints_load_balancer:
  identity:
    auth:
      octavia:
        region_name: "{{ openstack_helm_endpoints_octavia_region_name }}"
        username: "octavia-{{ openstack_helm_endpoints_octavia_region_name }}"
        password: "{{ openstack_helm_endpoints_octavia_keystone_password }}"
  load_balancer:
    scheme:
      public: https
    host_fqdn_override:
      public:
        host: "{{ openstack_helm_endpoints_octavia_api_host }}"
    port:
      api:
        public: 443
  oslo_db:
    auth:
      octavia:
        password: "{{ openstack_helm_endpoints_octavia_mariadb_password }}"
  oslo_messaging:
    auth:
      octavia:
        password: "{{ openstack_helm_endpoints_octavia_rabbitmq_password }}"

_openstack_helm_endpoints_cloudformation:
  cloudformation:
    scheme:
      public: https
    host_fqdn_override:
      public:
        host: "{{ openstack_helm_endpoints_heat_cfn_api_host }}"
    port:
      api:
        public: 443

_openstack_helm_endpoints_clustering:
  identity:
    auth:
      senlin:
        region_name: "{{ openstack_helm_endpoints_senlin_region_name }}"
        username: "senlin-{{ openstack_helm_endpoints_senlin_region_name }}"
        password: "{{ openstack_helm_endpoints_senlin_keystone_password }}"
  clustering:
    scheme:
      public: https
    host_fqdn_override:
      public:
        host: "{{ openstack_helm_endpoints_senlin_api_host }}"
    port:
      api:
        public: 443
  oslo_db:
    auth:
      senlin:
        password: "{{ openstack_helm_endpoints_senlin_mariadb_password }}"
  oslo_messaging:
    auth:
      senlin:
        password: "{{ openstack_helm_endpoints_senlin_rabbitmq_password }}"

_openstack_helm_endpoints_orchestration:
  identity:
    auth:
      heat:
        region_name: "{{ openstack_helm_endpoints_heat_region_name }}"
        username: "heat-{{ openstack_helm_endpoints_heat_region_name }}"
        password: "{{ openstack_helm_endpoints_heat_keystone_password }}"
      heat_trustee:
        region_name: "{{ openstack_helm_endpoints_heat_region_name }}"
        username: "heat-trustee-{{ openstack_helm_endpoints_heat_region_name }}"
        password: "{{ openstack_helm_endpoints_heat_trustee_keystone_password }}"
      heat_stack_user:
        region_name: "{{ openstack_helm_endpoints_heat_region_name }}"
        username: "heat-stack-user-{{ openstack_helm_endpoints_heat_region_name }}"
        password: "{{ openstack_helm_endpoints_heat_stack_user_keystone_password }}"
    path:
      public: /v3
  orchestration:
    scheme:
      public: https
    host_fqdn_override:
      public:
        host: "{{ openstack_helm_endpoints_heat_api_host }}"
    port:
      api:
        public: 443
  oslo_db:
    auth:
      heat:
        password: "{{ openstack_helm_endpoints_heat_mariadb_password }}"
  oslo_messaging:
    auth:
      heat:
        password: "{{ openstack_helm_endpoints_heat_rabbitmq_password }}"

_openstack_helm_endpoints_dashboard:
  dashboard:
    scheme:
      public: https
    host_fqdn_override:
      public:
        host: "{{ openstack_helm_endpoints_horizon_api_host }}"
    port:
      api:
        public: 443
  oslo_db:
    auth:
      horizon:
        password: "{{ openstack_helm_endpoints_horizon_mariadb_password }}"

_openstack_helm_endpoints_tempest:
  identity:
    auth:
      tempest:
        region_name: "{{ openstack_helm_endpoints_tempest_region_name }}"
        username: "tempest-{{ openstack_helm_endpoints_tempest_region_name }}"
        password: "{{ openstack_helm_endpoints_tempest_keystone_password }}"
