apiVersion: v2
appVersion: 1.5.1
description: Prometheus exporter for pluggable transceivers (SFP, SFP+, QSFP, etc.)
home: https://github.com/wobcom/transceiver-exporter
keywords:
- prometheus
- exporter
- transceiver
- sfp
- qsfp
- networking
maintainers:
- name: yaguangtang
name: transceiver-exporter
sources:
- https://github.com/wobcom/transceiver-exporter
type: application
version: 0.1.2
