---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# .. Copyright (C) 2022 VEXXHOST, Inc.
# .. SPDX-License-Identifier: Apache-2.0

# Default variables
# =================

# .. contents:: Sections
#    :local:


# .. envvar:: ceph_repository_apt_key [[[
#
# Ceph APT repository GPG key
ceph_repository_apt_key: "https://download.ceph.com/keys/release.asc"

                                                                   # ]]]
# .. envvar:: ceph_repository_url [[[
#
# Ceph APT repository URL
ceph_repository_url: https://download.ceph.com/debian-pacific/

                                                                   # ]]]
# .. envvar:: ceph_repository_version [[[
#
# Ceph version to pin package manager to
ceph_repository_version: 16.2.7

                                                                   # ]]]
