apiVersion: v2
appVersion: v1.0.0
dependencies:
- name: helm-toolkit
  repository: file://../helm-toolkit
  version: '>= 0.1.0'
description: OpenStack-Helm libvirt
home: https://libvirt.org
maintainers:
- name: OpenStack-Helm Authors
name: libvirt
sources:
- https://libvirt.org/git/?p=libvirt.git;a=summary
- https://opendev.org/openstack/openstack-helm
version: 1.1.0
