# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

_openstack_exporter_default_args:
  - --endpoint-type=internal
  - default
  - --collect-metric-time
  - --cache
  - --disable-metric=neutron-l3_agent_of_router
  - --disable-service.load-balancer
