---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# .. Copyright (C) 2022 VEXXHOST, Inc.
# .. SPDX-License-Identifier: Apache-2.0

# Default variables
# =================

# .. contents:: Sections
#    :local:


# .. envvar:: openstack_helm_heat_image_repository [[[
#
# Image repository location to be prefixed for all images
openstack_helm_heat_image_repository: "{{ atmosphere_image_repository | default('us-docker.pkg.dev/vexxhost-infra/openstack') }}"

                                                                   # ]]]
# .. envvar:: openstack_helm_heat_image_tag [[[
#
# Image tag for container
openstack_helm_heat_image_tag: wallaby

                                                                   # ]]]
# .. envvar:: openstack_helm_heat_auth_encryption_key [[[
#
# Unique value to use for encrypting Heat secrets
openstack_helm_heat_auth_encryption_key: "{{ undef(hint='You must specifiy an encryption key for Heat.') }}"

                                                                   # ]]]
# .. envvar:: openstack_helm_heat_diff [[[
#
# Disable a diff of the release values and ask for manual confirmation
openstack_helm_heat_diff: false

                                                                   # ]]]
# .. envvar:: openstack_helm_heat_migrate_from_mariadb [[[
#
# Execute a migration from legacy MariaDB to Percona XtraDB cluster
openstack_helm_heat_migrate_from_mariadb: false

                                                                   # ]]]
# .. envvar:: openstack_helm_heat_values [[[
#
# Overrides for Helm chart values
openstack_helm_heat_values: {}

                                                                   # ]]]
# .. envvar:: openstack_helm_heat_ingress_annotations [[[
#
# Ingress annotations
openstack_helm_heat_ingress_annotations: {}

                                                                   # ]]]
