# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- hosts: all
  become: true
  vars:
    work_dir: "{{ zuul.project.src_dir }}"
    logs_dir: "/tmp/logs"
  roles:
    - gather-host-logs
    - helm-release-status
    - describe-kubernetes-objects
    - gather-pod-logs
    - gather-prom-metrics
    - gather-selenium-data
