apiVersion: v2
appVersion: v1.14.2
dependencies:
- name: library
  repository: file://../library
  version: 0.0.1
description: File, Block, and Object Storage Services for your Cloud-Native Environment
icon: https://rook.io/images/rook-logo.svg
name: rook-ceph
sources:
- https://github.com/rook/rook
version: v1.14.2
