apiVersion: v1
appVersion: v1.0.0
description: OpenStack-Helm Horizon
home: https://docs.openstack.org/horizon/latest/
icon: https://www.openstack.org/themes/openstack/images/project-mascots/Horizon/OpenStack_Project_Horizon_vertical.png
maintainers:
- name: OpenStack-Helm Authors
name: horizon
sources:
- https://opendev.org/openstack/horizon
- https://opendev.org/openstack/openstack-helm
version: 0.3.1
