annotations:
  artifacthub.io/changes: |
    - kind: added
      description: topologySpreadConstraints can be templated values
apiVersion: v2
appVersion: 1.11.1
description: CoreDNS is a DNS server that chains plugins and provides Kubernetes DNS
  Services
home: https://coredns.io
icon: https://coredns.io/images/CoreDNS_Colour_Horizontal.png
keywords:
- coredns
- dns
- kubedns
maintainers:
- name: mrueg
- name: haad
- name: hagaibarel
- name: shubham-cmyk
name: coredns
sources:
- https://github.com/coredns/coredns
type: application
version: 1.28.0
