{{/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.manifests.job_storage_init }}
{{- $envAll := . }}

{{- $internal_ceph_backend := .Values.ceph_client.internal_ceph_backend }}

{{- $serviceAccountName := "cinder-storage-init" }}
{{ tuple $envAll "storage_init" $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $serviceAccountName }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $serviceAccountName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $serviceAccountName }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccountName }}
    namespace: {{ $envAll.Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cinder-storage-init
  labels:
{{ tuple $envAll "cinder" "storage-init" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
  annotations:
{{- if .Values.helm3_hook }}
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
{{- end }}
spec:
  template:
    metadata:
      labels:
{{ tuple $envAll "cinder" "storage-init" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
{{ dict "envAll" $envAll "application" "cinder" | include "helm-toolkit.snippets.kubernetes_pod_security_context" | indent 6 }}
      restartPolicy: OnFailure
{{ if $envAll.Values.pod.tolerations.cinder.enabled }}
{{ tuple $envAll "cinder" | include "helm-toolkit.snippets.kubernetes_tolerations" | indent 6 }}
{{ end }}
      nodeSelector:
        {{ .Values.labels.job.node_selector_key }}: {{ .Values.labels.job.node_selector_value }}
      initContainers:
{{ tuple $envAll "storage_init" list | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
        {{- if eq "true" (include "cinder.utils.has_ceph_backend" $envAll) }}
        - name: ceph-keyring-placement
{{ tuple $envAll "cinder_storage_init" | include "helm-toolkit.snippets.image" | indent 10 }}
          securityContext:
            runAsUser: 0
          command:
            - /tmp/ceph-admin-keyring.sh
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: etcceph
              mountPath: /etc/ceph
            - name: cinder-bin
              mountPath: /tmp/ceph-admin-keyring.sh
              subPath: ceph-admin-keyring.sh
              readOnly: true
            {{- if empty .Values.conf.ceph.admin_keyring }}
            - name: ceph-keyring
              mountPath: /tmp/client-keyring
              subPath: key
              readOnly: true
            {{ end }}
        {{ end }}
      containers:
        {{- range $name, $backend := .Values.conf.backends }}
          {{- if (eq "true" ( dict "backend" $backend | include "cinder.utils.is_ceph_backend" )) }}
        - name: cinder-storage-init-{{ $name | lower | replace "_" "-" }}
{{ tuple $envAll "cinder_storage_init" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ tuple $envAll $envAll.Values.pod.resources.jobs.storage_init | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STORAGE_BACKEND
              value: {{ $backend.volume_driver | quote }}
            - name: RBD_POOL_NAME
              value: {{ $backend.rbd_pool | quote }}
            - name: RBD_POOL_USER
              value: {{ $backend.rbd_user | quote }}
            {{- if eq $internal_ceph_backend $name }}
            - name: RBD_POOL_SECRET
              value: {{ $envAll.Values.secrets.rbd.volume | quote }}
            {{- else }}
            - name: RBD_POOL_SECRET
              value: "{{ $envAll.Values.secrets.rbd.volume }}-{{ $name | lower | replace "_" "-" }}"
            {{- end }}
            {{- $ec_pool := index $envAll.Values.conf.ceph.ec_pools $backend.rbd_pool }}
            {{- if $ec_pool }}
            - name: EC_ENABLED
              value: "true"
            - name: EC_PROFILE_NAME
              value: "{{ $backend.rbd_pool | replace "." "_" }}_profile"
            - name: EC_PROFILE_K
              value: {{ $ec_pool.data_pool.ec_profile.k | quote }}
            - name: EC_PROFILE_M
              value: {{ $ec_pool.data_pool.ec_profile.m | quote }}
            - name: EC_PROFILE_DEVICE_CLASS
              value: {{ $ec_pool.data_pool.ec_profile.crush_device_class | quote }}
            - name: EC_PROFILE_FAILURE_DOMAIN
              value: {{ $ec_pool.data_pool.ec_profile.crush_failure_domain | quote }}
            - name: EC_DATA_POOL_NAME
              value: "{{ $backend.rbd_pool }}.data"
            - name: EC_METADATA_POOL_CHUNK_SIZE
              value: {{ $ec_pool.metadata_pool.chunk_size | quote }}
            - name: EC_METADATA_POOL_REPLICATION
              value: {{ $ec_pool.metadata_pool.replication | quote }}
            - name: EC_METADATA_POOL_CRUSH_RULE
              value: {{ $ec_pool.metadata_pool.crush_rule | quote }}
            - name: EC_POOL_APP_NAME
              value: {{ $ec_pool.app_name | quote }}
            {{- else }}
            - name: EC_ENABLED
              value: "false"
            - name: RBD_POOL_APP_NAME
              value: {{ (index $envAll.Values.conf.ceph.pools $backend.rbd_pool).app_name | quote }}
            - name: RBD_POOL_CRUSH_RULE
              value: {{ (index $envAll.Values.conf.ceph.pools $backend.rbd_pool).crush_rule | quote }}
            - name: RBD_POOL_REPLICATION
              value: {{ (index $envAll.Values.conf.ceph.pools $backend.rbd_pool).replication | quote }}
            - name: RBD_POOL_CHUNK_SIZE
              value: {{ (index $envAll.Values.conf.ceph.pools $backend.rbd_pool).chunk_size | quote }}
            {{- end }}
          command:
            - /tmp/storage-init.sh
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: cinder-bin
              mountPath: /tmp/storage-init.sh
              subPath: storage-init.sh
              readOnly: true
            - name: etcceph
              mountPath: /etc/ceph
            - name: ceph-etc
              mountPath: /etc/ceph/ceph.conf
              subPath: ceph.conf
              readOnly: true
            {{- if empty $envAll.Values.conf.ceph.admin_keyring }}
            - name: ceph-keyring
              mountPath: /tmp/client-keyring
              subPath: key
              readOnly: true
            {{- end }}
        {{- end }}
      {{- end }}
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: cinder-bin
          configMap:
            name: cinder-bin
            defaultMode: 0555
        {{- if eq "true" (include "cinder.utils.has_ceph_backend" $envAll) }}
        - name: etcceph
          emptyDir: {}
        - name: ceph-etc
          configMap:
            name: {{ .Values.ceph_client.configmap }}
            defaultMode: 0444
        {{- if empty .Values.conf.ceph.admin_keyring }}
        - name: ceph-keyring
          secret:
            secretName: {{ .Values.ceph_client.user_secret_name }}
        {{- end }}
        {{- end }}
{{- end }}
