apiVersion: v1
appVersion: v1.0.0
description: OpenStack-Helm Designate
home: https://docs.openstack.org/designate/latest/
icon: https://www.openstack.org/themes/openstack/images/project-mascots/Designate/OpenStack_Project_Designate_vertical.jpg
maintainers:
- name: OpenStack-Helm Authors
name: designate
sources:
- https://opendev.org/openstack/designate
- https://opendev.org/openstack/openstack-helm
version: 0.2.11
