apiVersion: v1
appVersion: v1.0.0
description: OpenStack-Helm Heat
home: https://docs.openstack.org/heat/latest/
icon: https://www.openstack.org/themes/openstack/images/project-mascots/Heat/OpenStack_Project_Heat_vertical.png
maintainers:
- name: OpenStack-Helm Authors
name: heat
sources:
- https://opendev.org/openstack/heat
- https://opendev.org/openstack/openstack-helm
version: 0.3.12
