---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# .. Copyright (C) 2022 VEXXHOST, Inc.
# .. SPDX-License-Identifier: Apache-2.0

# Default variables
# =================

# .. contents:: Sections
#    :local:


# .. envvar:: openstack_helm_cinder_image_repository [[[
#
# Image repository location to be prefixed for all images
openstack_helm_cinder_image_repository: "{{ atmosphere_image_repository | default('quay.io/vexxhost') }}"

                                                                   # ]]]
# .. envvar:: openstack_helm_cinder_image_tag [[[
#
# Image tag for container
openstack_helm_cinder_image_tag: wallaby

                                                                   # ]]]
# .. envvar:: openstack_helm_cinder_heat_image_tag [[[
#
# Image tag for Heat to be used for jobs running via Helm hooks
openstack_helm_cinder_heat_image_tag: wallaby

                                                                   # ]]]
# .. envvar:: openstack_helm_cinder_values [[[
#
# Overrides for Helm chart values
openstack_helm_cinder_values: {}

                                                                   # ]]]
# .. envvar:: openstack_helm_cinder_ingress_annotations [[[
#
# Ingress annotations
openstack_helm_cinder_ingress_annotations: {}

                                                                   # ]]]
