# Copyright (c) 2023 VEXXHOST, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

_cert_manager_helm_values:
  installCRDs: true
  featureGates: AdditionalCertificateOutputFormats=true
  image:
    repository: "{{ atmosphere_images['cert_manager_controller'] | vexxhost.atmosphere.docker_image('name') }}"
    tag: "{{ atmosphere_images['cert_manager_controller'] | vexxhost.atmosphere.docker_image('tag') }}"
  volumes:
    - name: etc-ssl-certs
      hostPath:
        path: /etc/ssl/certs
  volumeMounts:
    - name: etc-ssl-certs
      mountPath: /etc/ssl/certs
      readOnly: true
  nodeSelector:
    openstack-control-plane: enabled
  webhook:
    extraArgs:
      - --feature-gates=AdditionalCertificateOutputFormats=true
    nodeSelector:
      openstack-control-plane: enabled
    image:
      repository: "{{ atmosphere_images['cert_manager_webhook'] | vexxhost.atmosphere.docker_image('name') }}"
      tag: "{{ atmosphere_images['cert_manager_webhook'] | vexxhost.atmosphere.docker_image('tag') }}"
  cainjector:
    nodeSelector:
      openstack-control-plane: enabled
    image:
      repository: "{{ atmosphere_images['cert_manager_cainjector'] | vexxhost.atmosphere.docker_image('name') }}"
      tag: "{{ atmosphere_images['cert_manager_cainjector'] | vexxhost.atmosphere.docker_image('tag') }}"
  startupapicheck:
    nodeSelector:
      openstack-control-plane: enabled
    image:
      repository: "{{ atmosphere_images['cert_manager_cli'] | vexxhost.atmosphere.docker_image('name') }}"
      tag: "{{ atmosphere_images['cert_manager_cli'] | vexxhost.atmosphere.docker_image('tag') }}"
