_percona_xtradb_cluster_spec:
  crVersion: "1.12.0"
  secretsName: percona-xtradb
  pxc:
    size: 3
    image: "{{ atmosphere_images['percona_xtradb_cluster'] | vexxhost.kubernetes.docker_image('ref') }}"
    autoRecovery: true
    configuration: |
      [mysqld]
      max_connections=8192
      innodb_buffer_pool_size=4096M
      max_allowed_packet=16M
      # Skip reverse DNS lookup of clients
      skip-name-resolve
    sidecars:
      - name: exporter
        image: "{{ atmosphere_images['prometheus_mysqld_exporter'] | vexxhost.kubernetes.docker_image('ref') }}"
        env:
          - name: MONITOR_PASSWORD
            valueFrom:
              secretKeyRef:
                name: percona-xtradb
                key: monitor
          - name: DATA_SOURCE_NAME
            value: "monitor:$(MONITOR_PASSWORD)@(localhost:3306)/"
        ports:
          - name: metrics
            containerPort: 9104
        livenessProbe:
          httpGet:
            port: metrics
            path: /
    nodeSelector:
      openstack-control-plane: enabled
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 160Gi
  haproxy:
    enabled: true
    size: 3
    image: "{{ atmosphere_images['percona_xtradb_cluster_haproxy'] | vexxhost.kubernetes.docker_image('ref') }}"
    nodeSelector:
      openstack-control-plane: enabled
