name: molecule

concurrency:
  group: molecule-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    paths:
    - .github/workflows/molecule.yml
    - molecule/**
    - playbooks/**
    - plugins/**
    - roles/**
  push:
    branches:
    - main
    paths:
    - .github/workflows/molecule.yml
    - molecule/**
    - playbooks/**
    - plugins/**
    - roles/**

jobs:
  wallaby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3.0.2

      - name: Set up Go
        uses: actions/setup-go@v3.3.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3.1.0
        with:
          args: release --rm-dist --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bundle Atmosphere CLI
        run: cp -v dist/*.tar.gz roles/atmosphere/files/

      - name: Clean-up stale stacks
        run: go run ./cmd/atmosphere-ci molecule cleanup
        env:
          OS_AUTH_URL: https://auth.vexxhost.net/v3
          OS_REGION_NAME: ca-ymq-1
          OS_USER_DOMAIN_NAME: Default
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
          OS_PROJECT_DOMAIN_NAME: Default
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}

      - uses: gofrolist/molecule-action@v2.2.41
        timeout-minutes: 90
        env:
          ATMOSPHERE_STACK_NAME: "atmosphere-${{ github.run_id }}-${{ github.run_attempt }}"
          OS_AUTH_URL: https://auth.vexxhost.net/v3
          OS_REGION_NAME: ca-ymq-1
          OS_USER_DOMAIN_NAME: Default
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
          OS_PROJECT_DOMAIN_NAME: Default
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
