# Name of the OpenStack-Helm Ingress to create
openstack_helm_ingress_name: "{{ openstack_helm_ingress_endpoint | replace('_', '-') }}"

# List of annotations to apply to the Ingress
openstack_helm_ingress_annotations: {}

# Hostname to expose for the Ingress
openstack_helm_ingress_host: "{{ openstack_helm_endpoints[openstack_helm_ingress_endpoint]['host_fqdn_override']['public']['host'] }}"

# Name of the "cert-manager" ClusterIssuer to use for TLS certificates
openstack_helm_ingress_cluster_issuer: "{{ atmosphere_ingress_cluster_issuer }}"

# Name of the Ingress class to use for exposing the service.
openstack_helm_ingress_class_name: "{{ atmosphere_ingress_class_name }}"

# Secret containing the TLS certificate to use for the Ingress, overriding this
# value globally should allow to point towards a secret containing the custom
# certificate.
#
# See: https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
openstack_helm_ingress_secret_name: "{{ openstack_helm_ingress_service_name }}-certs"
